# Copyright 2026 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

from enum import Enum
from typing import Any, Optional, Sequence, Tuple, Union


class DataType(Enum):
    bool = ...
    float16 = ...
    bfloat16 = ...
    float32 = ...
    int32 = ...
    int64 = ...



class NDObject:
    def shape(self) -> Tuple[int, ...]: ...
    def dtype(self) -> str: ...


class IntArrayRef:
    def __init__(self) -> None: ...
    def __init__(self, shape: Sequence[int]) -> None: ...
    def shape(self) -> Tuple[int, ...]: ...
    def update(self, shape: Sequence[int]) -> None: ...


class ScalarRef:
    def update(self, value: Union[int, float]) -> None: ...


ShapeLike = Union[Sequence[int], IntArrayRef]
BinaryInput = Union[NDObject, int, float, NDSymInt, NDSymFloat]
ScalarInput = Union[int, float, NDSymInt, NDSymFloat]


class KernelBase:
    def load(self, shape: ShapeLike, type: DataType) -> NDObject: ...
    def view_load(self, shape: ShapeLike, stride: ShapeLike, offset: int, type: DataType) -> NDObject: ...
    def store(self, obj: NDObject) -> NDObject: ...
    def scalar(self) -> ScalarRef: ...
    def int_array(self) -> IntArrayRef: ...
    def make_int(self) -> NDSymInt: ...
    def make_float(self) -> NDSymFloat: ...
    def sqrt(self, input: NDObject) -> NDObject: ...
    def abs(self, input: NDObject) -> NDObject: ...
    def log(self, input: NDObject) -> NDObject: ...
    def exp(self, input: NDObject) -> NDObject: ...
    def reciprocal(self, input: NDObject) -> NDObject: ...
    def isfinite(self, input: NDObject) -> NDObject: ...
    def logical_not(self, input: NDObject) -> NDObject: ...
    def round(self, input: NDObject) -> NDObject: ...
    def floor(self, input: NDObject) -> NDObject: ...
    def ceil(self, input: NDObject) -> NDObject: ...
    def trunc(self, input: NDObject) -> NDObject: ...
    def cast(self, input: NDObject, type: DataType) -> NDObject: ...
    def element_any(self, input: NDObject) -> NDObject: ...
    def equal(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def not_equal(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def greater(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def greater_equal(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def less(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def less_equal(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def add(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def sub(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def mul(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def div(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def pow(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def maximum(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def minimum(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def logical_and(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def logical_or(self, lhs: BinaryInput, rhs: BinaryInput) -> NDObject: ...
    def select(self, cond: NDObject, lhs: NDObject, rhs: NDObject) -> NDObject: ...
    def broadcast(self, input: NDObject, shape: ShapeLike) -> NDObject: ...
    def full(self, scalar: ScalarInput, shape: ShapeLike, dtype: DataType) -> NDObject: ...
    def reshape(self, input: NDObject, shape: ShapeLike) -> NDObject: ...
    def sum(self, input: NDObject, dims: Sequence[int], keepdims: bool = ...) -> NDObject: ...
    def max(self, input: NDObject, dims: Sequence[int], keepdims: bool = ...) -> NDObject: ...
    def min(self, input: NDObject, dims: Sequence[int], keepdims: bool = ...) -> NDObject: ...
    def copy(self, input: NDObject) -> NDObject: ...
    def matmul(
        self,
        lhs: NDObject,
        rhs: NDObject,
        trans_a: bool,
        trans_b: bool,
        bias: Optional[NDObject] = ...,
    ) -> NDObject: ...
    def grouped_matmul(
        self,
        lhs: NDObject,
        rhs: NDObject,
        trans_a: bool,
        trans_b: bool,
        bias: Optional[NDObject],
        group_list: Optional[NDObject],
        group_type: int,
        group_list_type: int = ...,
    ) -> NDObject: ...
    def das(self) -> str: ...
    def dump(self) -> str: ...
    def p_next(self) -> None: ...
    def spec_next(self) -> None: ...
    @staticmethod
    def set_deterministic(enable: bool) -> None: ...
    @staticmethod
    def set_online_tuning(enable: bool) -> None: ...


class Kernel(KernelBase):
    def __init__(self, ker_type: str, run_type: str, dev_id: int) -> None: ...
    def slice_load(self, shape: ShapeLike, start: Sequence[int], size: Sequence[int], type: DataType) -> NDObject: ...
    def stridedslice_load(
        self,
        shape: ShapeLike,
        start: Sequence[int],
        end: Sequence[int],
        step: Sequence[int],
        type: DataType,
    ) -> NDObject: ...
    def multi_load(self, shape: ShapeLike, type: DataType) -> NDObject: ...
    def pad_store(self, obj: NDObject, pad_shape: int) -> NDObject: ...
    def set_store_inplace(self, store: NDObject) -> None: ...
    def one_hot(
        self,
        indices: NDObject,
        depth: int,
        axis: int,
        on_value: Any,
        off_value: Any,
        dtype: DataType,
    ) -> NDObject: ...
    def allreduce(self, type: str, input: NDObject) -> NDObject: ...
    def allgather(self, input: NDObject) -> NDObject: ...
    def allgatherv2(self, input: NDObject) -> NDObject: ...
    def reducescatter(self, input: NDObject) -> NDObject: ...
    def convert_to_bf16(self, input: Any) -> Any: ...
    def convert_from_bf16(self, input: Any) -> Any: ...
    def seq_add(self, ker_type: str) -> None: ...
    def reset(self) -> None: ...
    def input(self, load: NDObject, array: Any) -> None: ...
    def output(self, store: NDObject) -> Any: ...
    def clear_store_memory(self, store: NDObject) -> None: ...
    def tile(self, start: int, end: int, num: int, factor: int = ...) -> None: ...
    def codegen(self, pass_names: Optional[Sequence[str]] = ...) -> None: ...
    def perf(self) -> Tuple[float, float, float]: ...
    def msprof(self, path: str, test_num: int) -> None: ...
    def run(self) -> None: ...
    def dry_run(self, core_idx: int, cube_core: bool) -> None: ...
    @staticmethod
    def init_comm(rank_id: int, rank_size: int, comm_type: str) -> None: ...
    @staticmethod
    def set_cube_store_type(type: int) -> None: ...
    @staticmethod
    def fork(size: int, comm_type: str = ...) -> None: ...
    @staticmethod
    def join() -> None: ...
    @staticmethod
    def barrier() -> None: ...
    @staticmethod
    def rank_id() -> int: ...
    @staticmethod
    def rank_size() -> int: ...


class Device:
    @staticmethod
    def arch() -> str: ...
    @staticmethod
    def core_num() -> int: ...
    @staticmethod
    def soc_name() -> str: ...


__all__ = [
    "DataType",
    "Device",
    "Kernel",
    "KernelBase",
    "NDObject",
    "NDSymFloat",
    "NDSymInt",
    "ShapeRef",
]

bool: DataType
float16: DataType
bfloat16: DataType
float32: DataType
int32: DataType
int64: DataType
